//! `brainclaw onboard` — interactive setup wizard.
//!
//! The wizard walks the operator through the smallest config that can
//! start a useful daemon: a provider + API key, persona, memory,
//! skills, sandbox, pairing, admin token and (optionally) a
//! service-manager unit.
//!
//! Runs interactively by default via [`dialoguer`]. Pass
//! `--non-interactive` to accept every default and source credentials
//! from the ambient environment (useful for CI smoke tests).
//!
//! The wizard never writes the API key or the admin token to a log
//! file. The admin token is generated by a CSPRNG and printed to stdout
//! exactly once — the user is responsible for copying it into their
//! password manager.

use std::collections::HashMap;
use std::io::IsTerminal;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use clap::Args;
use rand::TryRngCore;

use crate::config::{
    BrainClawConfig, MemorySection, PairingSection, PersonaSection, SandboxConfig, SecuritySection,
    SkillsSection,
};
use crate::doctor;

/// Command-line flags for `brainclaw onboard`.
#[derive(Debug, Clone, Args, Default)]
pub struct OnboardArgs {
    /// Target path for the written config. Defaults to
    /// `~/.brainclaw/brainclaw.toml`.
    #[arg(long)]
    pub config: Option<String>,
    /// Accept every default and read credentials from env vars.
    #[arg(long)]
    pub non_interactive: bool,
    /// Skip installing a systemd/launchd unit at the end.
    #[arg(long)]
    pub skip_service: bool,
    /// Skip running `doctor` at the end.
    #[arg(long)]
    pub skip_doctor: bool,
    /// When combined with `--non-interactive`, overwrite an existing file.
    #[arg(long)]
    pub force: bool,
}

/// Result of a non-interactive onboarding run — useful for tests.
#[derive(Debug)]
pub struct OnboardOutcome {
    /// Path that the config was written to.
    pub config_path: PathBuf,
    /// Generated admin token (also embedded in the config).
    pub admin_token: String,
}

/// Top-level entry point invoked from `main.rs`.
pub async fn run(args: &OnboardArgs) -> Result<()> {
    let target = resolve_target_path(args.config.as_deref())?;

    if args.non_interactive {
        let outcome = run_non_interactive(&target, &NonInteractiveEnv::from_process(), args.force)?;
        println!(
            "\nwrote {} (non-interactive)\nadmin token: {}\n(store this token — the daemon won't print it again)",
            outcome.config_path.display(),
            outcome.admin_token
        );
        if !args.skip_doctor {
            run_doctor_on(&outcome.config_path).await?;
        }
        return Ok(());
    }

    if !std::io::stdin().is_terminal() {
        bail!("onboard requires an interactive TTY — pass --non-interactive to run with defaults");
    }

    let outcome = run_interactive(&target).await?;

    if !args.skip_service {
        maybe_install_service()?;
    }

    if !args.skip_doctor {
        run_doctor_on(&outcome.config_path).await?;
    }

    print_summary(&outcome);
    Ok(())
}

fn resolve_target_path(override_path: Option<&str>) -> Result<PathBuf> {
    if let Some(p) = override_path {
        return Ok(PathBuf::from(expand_tilde_str(p)));
    }
    match dirs::home_dir() {
        Some(h) => Ok(h.join(".brainclaw").join("brainclaw.toml")),
        None => bail!("cannot resolve $HOME for default config path"),
    }
}

/// Environment snapshot used by the non-interactive path. Abstracted for
/// tests so we can feed fake env vars without mutating the process.
pub struct NonInteractiveEnv {
    vars: HashMap<String, String>,
}

impl NonInteractiveEnv {
    /// Snapshot of the current process environment.
    pub fn from_process() -> Self {
        Self {
            vars: std::env::vars().collect(),
        }
    }

    /// Build a fake env for tests.
    pub fn from_map(vars: HashMap<String, String>) -> Self {
        Self { vars }
    }

    fn get(&self, key: &str) -> Option<&str> {
        self.vars.get(key).map(|s| s.as_str())
    }
}

/// Run the non-interactive path. Also used by tests.
///
/// Produces a config populated with sensible defaults, a freshly-generated
/// admin token, and optionally an inline API key pulled from the env.
pub fn run_non_interactive(
    target: &Path,
    env: &NonInteractiveEnv,
    force: bool,
) -> Result<OnboardOutcome> {
    if target.exists() && !force {
        bail!(
            "{} already exists — pass --force to overwrite",
            target.display()
        );
    }

    let mut cfg = BrainClawConfig::default();

    // Provider: default to anthropic unless OPENAI_API_KEY is the only one set.
    let (provider, env_var) = pick_default_provider(env);
    cfg.provider.default_provider = provider.to_string();
    cfg.provider.api_key_env = Some(env_var.to_string());
    cfg.provider.default_model = Some(default_model_for(provider).to_string());

    // Persona — use built-in defaults.
    cfg.persona.name = "BrainClaw".into();

    // Memory & skills
    cfg.memory = MemorySection::default();
    cfg.skills = SkillsSection {
        enabled: false,
        directories: Vec::new(),
        registry_url: None,
    };

    // Sandbox defaults are already set in SandboxConfig::default (docker + none).
    let _ = SandboxConfig::default();

    // Pairing: leave defaults.
    cfg.pairing = PairingSection::default();

    // Admin token.
    let admin_token = generate_admin_token();
    cfg.security.admin_token = Some(admin_token.clone());

    write_config(target, &cfg)?;

    Ok(OnboardOutcome {
        config_path: target.to_path_buf(),
        admin_token,
    })
}

fn pick_default_provider(env: &NonInteractiveEnv) -> (&'static str, &'static str) {
    if env.get("ANTHROPIC_API_KEY").is_some() {
        ("anthropic", "ANTHROPIC_API_KEY")
    } else if env.get("OPENAI_API_KEY").is_some() {
        ("openai", "OPENAI_API_KEY")
    } else if env.get("GOOGLE_API_KEY").is_some() {
        ("google", "GOOGLE_API_KEY")
    } else if env.get("GROQ_API_KEY").is_some() {
        ("groq", "GROQ_API_KEY")
    } else {
        // Default to anthropic; the operator will need to set the env var
        // before `brainclaw serve` works.
        ("anthropic", "ANTHROPIC_API_KEY")
    }
}

fn default_model_for(provider: &str) -> &'static str {
    match provider {
        "anthropic" => "claude-sonnet-4-5",
        "openai" => "gpt-4o",
        "google" | "gemini" => "gemini-2.0-flash",
        "groq" => "llama-3.3-70b-versatile",
        "ollama" => "llama3.1",
        _ => "claude-sonnet-4-5",
    }
}

async fn run_interactive(target: &Path) -> Result<OnboardOutcome> {
    use dialoguer::{Confirm, Input, Password, Select, theme::ColorfulTheme};

    print_banner();

    // 1. Target path
    let target: PathBuf = {
        let default = target.to_string_lossy().into_owned();
        let entered: String = Input::with_theme(&ColorfulTheme::default())
            .with_prompt("Config path")
            .default(default)
            .interact_text()?;
        let p = PathBuf::from(expand_tilde_str(&entered));
        if p.exists() {
            let confirmed = Confirm::with_theme(&ColorfulTheme::default())
                .with_prompt(format!("{} exists — overwrite?", p.display()))
                .default(false)
                .interact()?;
            if !confirmed {
                bail!("aborted by user");
            }
        }
        p
    };

    let mut cfg = BrainClawConfig::default();

    // 2. Provider
    let providers = ["anthropic", "openai", "google", "ollama"];
    let provider_idx = Select::with_theme(&ColorfulTheme::default())
        .with_prompt("AI provider")
        .items(&providers)
        .default(0)
        .interact()?;
    let provider = providers[provider_idx];
    cfg.provider.default_provider = provider.into();

    // 3. API key
    let env_var_name = match provider {
        "anthropic" => "ANTHROPIC_API_KEY",
        "openai" => "OPENAI_API_KEY",
        "google" => "GOOGLE_API_KEY",
        _ => "",
    };
    if !env_var_name.is_empty() {
        let use_env = Confirm::with_theme(&ColorfulTheme::default())
            .with_prompt(format!(
                "Read API key from env var `{env_var_name}`? (No = enter inline)"
            ))
            .default(true)
            .interact()?;
        if use_env {
            cfg.provider.api_key_env = Some(env_var_name.into());
            if std::env::var(env_var_name).is_err() {
                tracing::info!(
                    "env var {env_var_name} is not set in the current shell — set it before running `brainclaw serve`"
                );
            }
        } else {
            let key: String = Password::with_theme(&ColorfulTheme::default())
                .with_prompt(format!("{provider} API key"))
                .allow_empty_password(false)
                .interact()?;
            cfg.provider.api_key = Some(key);
        }
    }

    // 4. Default model
    let default_model = default_model_for(provider);
    let model: String = Input::with_theme(&ColorfulTheme::default())
        .with_prompt("Default model")
        .default(default_model.into())
        .interact_text()?;
    cfg.provider.default_model = Some(model);

    // 5. Persona
    let persona: String = Input::with_theme(&ColorfulTheme::default())
        .with_prompt("Persona name")
        .default("BrainClaw".into())
        .interact_text()?;
    cfg.persona = PersonaSection {
        name: persona,
        system_prompt: None,
        system_prompt_file: None,
        context_files: Vec::new(),
    };

    // 6. System prompt source
    let prompt_choices = ["built-in default", "inline text", "file path"];
    let prompt_idx = Select::with_theme(&ColorfulTheme::default())
        .with_prompt("System prompt source")
        .items(&prompt_choices)
        .default(0)
        .interact()?;
    match prompt_idx {
        1 => {
            let inline: String = Input::with_theme(&ColorfulTheme::default())
                .with_prompt("System prompt text")
                .allow_empty(false)
                .interact_text()?;
            cfg.persona.system_prompt = Some(inline);
        }
        2 => {
            let path: String = Input::with_theme(&ColorfulTheme::default())
                .with_prompt("Path to prompt file")
                .interact_text()?;
            cfg.persona.system_prompt_file = Some(path);
        }
        _ => {}
    }

    // 7. Memory
    let memory_enabled = Confirm::with_theme(&ColorfulTheme::default())
        .with_prompt("Enable conversation memory?")
        .default(true)
        .interact()?;
    let storage_dir: String = if memory_enabled {
        Input::with_theme(&ColorfulTheme::default())
            .with_prompt("Memory storage directory")
            .default("~/.brainclaw/memory".into())
            .interact_text()?
    } else {
        "~/.brainclaw/memory".into()
    };
    cfg.memory = MemorySection {
        enabled: memory_enabled,
        storage_dir,
        max_history_messages: 100,
        persist_conversations: memory_enabled,
    };

    // 8. Skills
    let skills_enabled = Confirm::with_theme(&ColorfulTheme::default())
        .with_prompt("Enable SKILL.md skill system?")
        .default(true)
        .interact()?;
    let mut skills_section = SkillsSection::default();
    if skills_enabled {
        let default_dirs = "./skills,~/.brainclaw/skills";
        let dirs_csv: String = Input::with_theme(&ColorfulTheme::default())
            .with_prompt("Skill directories (comma-separated)")
            .default(default_dirs.into())
            .interact_text()?;
        skills_section.enabled = true;
        skills_section.directories = dirs_csv
            .split(',')
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .collect();
        let registry_url: String = Input::with_theme(&ColorfulTheme::default())
            .with_prompt("Skill registry URL (blank = none)")
            .allow_empty(true)
            .default(String::new())
            .interact_text()?;
        if !registry_url.is_empty() {
            skills_section.registry_url = Some(registry_url);
        }
    }
    cfg.skills = skills_section;

    // 9. Sandbox
    let sandbox_enabled = Confirm::with_theme(&ColorfulTheme::default())
        .with_prompt("Enable container sandbox for dangerous tool calls?")
        .default(true)
        .interact()?;
    let mut sandbox = SandboxConfig {
        enabled: sandbox_enabled,
        ..SandboxConfig::default()
    };
    if sandbox_enabled {
        let runtimes = ["docker", "podman", "host (unsafe, dev only)"];
        let rt_idx = Select::with_theme(&ColorfulTheme::default())
            .with_prompt("Sandbox runtime")
            .items(&runtimes)
            .default(0)
            .interact()?;
        sandbox.runtime = match rt_idx {
            0 => "docker".into(),
            1 => "podman".into(),
            _ => "host".into(),
        };
        if sandbox.runtime != "host" {
            let img: String = Input::with_theme(&ColorfulTheme::default())
                .with_prompt("Sandbox image")
                .default(sandbox.image.clone())
                .interact_text()?;
            sandbox.image = img;
        }
        let nets = ["none", "full", "limited"];
        let net_idx = Select::with_theme(&ColorfulTheme::default())
            .with_prompt("Network policy")
            .items(&nets)
            .default(0)
            .interact()?;
        sandbox.network = nets[net_idx].to_string();
        if sandbox.network == "limited" {
            let hosts_csv: String = Input::with_theme(&ColorfulTheme::default())
                .with_prompt("Allowed hosts (comma-separated, * wildcards OK)")
                .allow_empty(true)
                .default(String::new())
                .interact_text()?;
            sandbox.allowed_hosts = hosts_csv
                .split(',')
                .map(|s| s.trim().to_string())
                .filter(|s| !s.is_empty())
                .collect();
        }
    }
    cfg.sandbox = sandbox;

    // 10. Pairing — default policy, maybe pre-approve one admin user.
    cfg.pairing = PairingSection::default();
    let pre_approve = Confirm::with_theme(&ColorfulTheme::default())
        .with_prompt("Pre-approve an admin user for DM pairing?")
        .default(false)
        .interact()?;
    if pre_approve {
        let peer: String = Input::with_theme(&ColorfulTheme::default())
            .with_prompt("Peer (format: <channel>:<user_id>, e.g. discord:123456)")
            .interact_text()?;
        if !peer.is_empty() {
            cfg.pairing.allow_from.push(peer);
        }
    }

    // 11. Admin token.
    let admin_token = generate_admin_token();
    cfg.security = SecuritySection {
        admin_token: Some(admin_token.clone()),
        ..cfg.security
    };

    // 12. Channels.
    let channel_names = [
        "discord",
        "telegram",
        "slack",
        "matrix",
        "mattermost",
        "whatsapp",
        "signal",
    ];
    let mut enabled_channels: Vec<String> = Vec::new();
    for ch in channel_names {
        let want = Confirm::with_theme(&ColorfulTheme::default())
            .with_prompt(format!("Enable `{ch}` channel?"))
            .default(false)
            .interact()?;
        if want {
            enabled_channels.push(ch.into());
            let env_var = channel_env_var(ch).unwrap_or("");
            if !env_var.is_empty() && std::env::var(env_var).is_err() {
                println!(
                    "  (reminder: export {env_var} before `brainclaw serve` — secrets are NOT written to the config file)"
                );
            }
        }
    }
    cfg.security.allowed_channel_types = enabled_channels;

    // 13. Write config.
    write_config(&target, &cfg)?;

    Ok(OnboardOutcome {
        config_path: target,
        admin_token,
    })
}

fn print_banner() {
    println!(
        r#"
 ______           _       _____ _
 | ___ \         (_)     /  __ \ |
 | |_/ /_ __ __ _ _ _ __ | /  \/ | __ ___      __
 | ___ \ '__/ _` | | '_ \| |   | |/ _` \ \ /\ / /
 | |_/ / | | (_| | | | | | \__/\ | (_| |\ V  V /
 \____/|_|  \__,_|_|_| |_|\____/_|\__,_| \_/\_/

 BrainClaw — personal AI assistant daemon
 Setup wizard: answers sensible defaults; everything is editable in the written TOML file.
"#
    );
}

fn print_summary(outcome: &OnboardOutcome) {
    println!();
    println!("✔ wrote {}", outcome.config_path.display());
    println!();
    println!("Admin token (SAVE THIS — it is shown only once):");
    println!("  {}", outcome.admin_token);
    println!();
    println!("Next steps:");
    println!("  1. Export any channel credential env vars you enabled.");
    println!("  2. Run `brainclaw serve` to start the daemon.");
    println!("  3. Open http://localhost:18789/admin/ui for the dashboard.");
}

fn channel_env_var(channel: &str) -> Option<&'static str> {
    Some(match channel {
        "discord" => "DISCORD_TOKEN",
        "telegram" => "TELEGRAM_BOT_TOKEN",
        "slack" => "SLACK_BOT_TOKEN",
        "matrix" => "MATRIX_ACCESS_TOKEN",
        "mattermost" => "MATTERMOST_TOKEN",
        "whatsapp" => "WHATSAPP_ACCESS_TOKEN",
        "signal" => "SIGNAL_PHONE_NUMBER",
        _ => return None,
    })
}

/// Serialise `cfg` as TOML and write it to `path`, creating parent dirs.
pub fn write_config(path: &Path, cfg: &BrainClawConfig) -> Result<()> {
    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
    {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating config parent directory {}", parent.display()))?;
    }
    let toml_str = toml::to_string_pretty(cfg).context("serialising BrainClawConfig to TOML")?;
    std::fs::write(path, toml_str)
        .with_context(|| format!("writing config to {}", path.display()))?;
    tracing::info!(path = %path.display(), "onboard: wrote config");
    Ok(())
}

/// Generate a URL-safe hex admin token from the OS CSPRNG.
pub fn generate_admin_token() -> String {
    let mut buf = [0u8; 32];
    // `OsRng` is fallible in rand 0.9 (it wraps `getrandom`). If the OS
    // can't produce entropy, that's a hard failure — panic is appropriate.
    rand::rngs::OsRng
        .try_fill_bytes(&mut buf)
        .expect("OS CSPRNG must not fail when generating the admin token");
    hex::encode(buf)
}

fn maybe_install_service() -> Result<()> {
    #[cfg(target_os = "linux")]
    {
        use dialoguer::{Confirm, theme::ColorfulTheme};
        let confirmed = Confirm::with_theme(&ColorfulTheme::default())
            .with_prompt("Install a systemd --user unit for brainclaw?")
            .default(false)
            .interact()?;
        if confirmed {
            install_systemd_user_unit()?;
        }
        Ok(())
    }
    #[cfg(target_os = "macos")]
    {
        use dialoguer::{Confirm, theme::ColorfulTheme};
        let confirmed = Confirm::with_theme(&ColorfulTheme::default())
            .with_prompt("Install a launchd plist for brainclaw?")
            .default(false)
            .interact()?;
        if confirmed {
            install_launchd_plist()?;
        }
        Ok(())
    }
    #[cfg(not(any(target_os = "linux", target_os = "macos")))]
    {
        println!("service install not supported on this OS — start `brainclaw serve` manually");
        Ok(())
    }
}

#[cfg(target_os = "linux")]
fn install_systemd_user_unit() -> Result<()> {
    let home = dirs::home_dir().context("resolving $HOME for systemd unit install")?;
    let unit_dir = home.join(".config").join("systemd").join("user");
    std::fs::create_dir_all(&unit_dir)
        .with_context(|| format!("creating {}", unit_dir.display()))?;
    let unit_path = unit_dir.join("brainclaw.service");
    let exe = std::env::current_exe()
        .unwrap_or_else(|_| PathBuf::from("brainclaw"))
        .to_string_lossy()
        .into_owned();
    let unit = format!(
        "[Unit]\n\
        Description=BrainClaw personal AI assistant daemon\n\
        After=network-online.target\n\
        \n\
        [Service]\n\
        Type=simple\n\
        ExecStart={exe} serve\n\
        Restart=on-failure\n\
        RestartSec=5\n\
        \n\
        [Install]\n\
        WantedBy=default.target\n",
    );
    std::fs::write(&unit_path, unit).with_context(|| format!("writing {}", unit_path.display()))?;
    println!(
        "✔ wrote {}\n  next: `systemctl --user daemon-reload && systemctl --user enable --now brainclaw`",
        unit_path.display()
    );
    Ok(())
}

#[cfg(target_os = "macos")]
fn install_launchd_plist() -> Result<()> {
    let home = dirs::home_dir().context("resolving $HOME for launchd plist install")?;
    let plist_dir = home.join("Library").join("LaunchAgents");
    std::fs::create_dir_all(&plist_dir)
        .with_context(|| format!("creating {}", plist_dir.display()))?;
    let plist_path = plist_dir.join("com.brainwires.brainclaw.plist");
    let exe = std::env::current_exe()
        .unwrap_or_else(|_| PathBuf::from("brainclaw"))
        .to_string_lossy()
        .into_owned();
    let plist = format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.brainwires.brainclaw</string>
  <key>ProgramArguments</key>
  <array>
    <string>{exe}</string>
    <string>serve</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
</dict>
</plist>
"#,
    );
    std::fs::write(&plist_path, plist)
        .with_context(|| format!("writing {}", plist_path.display()))?;
    println!(
        "✔ wrote {}\n  next: `launchctl load {}`",
        plist_path.display(),
        plist_path.display()
    );
    Ok(())
}

async fn run_doctor_on(path: &Path) -> Result<()> {
    let cfg = BrainClawConfig::load(path)
        .with_context(|| format!("re-loading written config {}", path.display()))?;
    println!("\n— running doctor on the new config —");
    let results = doctor::run_doctor_with_config(&cfg).await;
    let mut fails = 0;
    for r in &results {
        println!("  [{}] {}: {}", status_label(&r.status), r.name, r.detail);
        if r.status == doctor::Status::Fail {
            fails += 1;
        }
    }
    println!("\n{} checks, {fails} fail(s)", results.len());
    Ok(())
}

fn status_label(s: &doctor::Status) -> &'static str {
    match s {
        doctor::Status::Pass => "PASS",
        doctor::Status::Warn => "WARN",
        doctor::Status::Fail => "FAIL",
        doctor::Status::Skip => "SKIP",
    }
}

fn expand_tilde_str(path: &str) -> String {
    if let Some(rest) = path.strip_prefix("~/")
        && let Some(home) = dirs::home_dir()
    {
        return home.join(rest).to_string_lossy().into_owned();
    }
    path.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_admin_token_is_32_bytes_hex() {
        let t = generate_admin_token();
        assert_eq!(t.len(), 64, "expected 32-byte hex token, got {t:?}");
        assert!(
            t.chars().all(|c| c.is_ascii_hexdigit()),
            "non-hex char in token: {t}"
        );
    }

    #[test]
    fn pick_default_provider_prefers_anthropic() {
        let env = NonInteractiveEnv::from_map(
            [("ANTHROPIC_API_KEY".into(), "x".into())]
                .into_iter()
                .collect(),
        );
        assert_eq!(pick_default_provider(&env).0, "anthropic");
    }
}
