// Fetch the JSR score breakdown for every @rullama package and write docs/jsr-scores.md.
//
//   deno task jsr:scores
//
// The score factors that are settings-only (description, provenance, runtime
// compatibility flags) are set in the JSR web UI / by the publish workflow; the
// code-side ones (README example, entrypoint docs, documented symbols) are gated
// by `deno task doc-lint` and the per-package READMEs. This table shows both.

const SCOPE = "rullama";
const API = `https://jsr.io/api/scopes/${SCOPE}/packages`;

interface Score {
  total: number;
  hasReadme: boolean;
  hasReadmeExamples: boolean;
  allEntrypointsDocs: boolean;
  percentageDocumentedSymbols: number;
  allFastCheck: boolean;
  hasProvenance: boolean;
  hasDescription: boolean;
  atLeastOneRuntimeCompatible: boolean;
  multipleRuntimesCompatible: boolean;
}

interface PackageRow {
  name: string;
  latestVersion: string | null;
  score: number | null;
}

async function json<T>(url: string): Promise<T> {
  const res = await fetch(url, { signal: AbortSignal.timeout(15_000) });
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  return await res.json() as T;
}

const mark = (ok: boolean): string => ok ? "✓" : "✗";

const packages = (await json<{ items: PackageRow[] }>(`${API}?limit=100`)).items
  .sort((a, b) => a.name.localeCompare(b.name));

const lines = [
  "# JSR scores",
  "",
  `Generated by \`deno task jsr:scores\` on ${
    new Date().toISOString().slice(0, 10)
  }.`,
  "",
  "| Package | Version | Score | README ex. | Entrypoint docs | Symbols documented | Description | Provenance | Runtimes |",
  "|---|---|---:|:-:|:-:|---:|:-:|:-:|:-:|",
];
for (const pkg of packages) {
  const s = await json<Score>(`${API}/${pkg.name}/score`);
  lines.push(
    `| ${pkg.name} | ${pkg.latestVersion ?? "-"} | ${s.total} | ${
      mark(s.hasReadmeExamples)
    } | ${mark(s.allEntrypointsDocs)} | ${
      Math.round(s.percentageDocumentedSymbols * 100)
    }% | ${mark(s.hasDescription)} | ${mark(s.hasProvenance)} | ${
      s.multipleRuntimesCompatible
        ? "multi"
        : s.atLeastOneRuntimeCompatible
        ? "one"
        : "✗"
    } |`,
  );
}
await Deno.writeTextFile("docs/jsr-scores.md", lines.join("\n") + "\n");
console.log(`wrote docs/jsr-scores.md (${packages.length} packages)`);
