/**
 * Cross-language serialization verification tests.
 *
 * Reads JSON fixture files generated by the Rust `generate_json_fixtures` test
 * (or hand-crafted equivalents) and verifies that each fixture has the expected
 * shape and round-trips correctly through JSON.parse / JSON.stringify.
 *
 * Run with: deno test deno/tests/fixture_test.ts
 */

import { assertEquals, assertExists } from "@std/assert";
import { join } from "@std/path";

const FIXTURES_DIR = join(
  new URL(".", import.meta.url).pathname,
  "..",
  "fixtures",
);

/** Read and parse a fixture JSON file. */
function loadFixture<T = unknown>(name: string): T {
  const path = join(FIXTURES_DIR, `${name}.json`);
  const text = Deno.readTextFileSync(path);
  return JSON.parse(text) as T;
}

/** Assert that a value round-trips through JSON serialization. */
function assertRoundTrip(value: unknown, label: string): void {
  const serialized = JSON.stringify(value);
  const deserialized = JSON.parse(serialized);
  assertEquals(deserialized, value, `${label} failed round-trip`);
}

// ── 1. Role ──────────────────────────────────────────────────────────────────

Deno.test("Role: user variant", () => {
  const role = loadFixture<string>("role_user");
  assertEquals(role, "user");
  assertRoundTrip(role, "Role::User");
});

Deno.test("Role: assistant variant", () => {
  const role = loadFixture<string>("role_assistant");
  assertEquals(role, "assistant");
  assertRoundTrip(role, "Role::Assistant");
});

Deno.test("Role: system variant", () => {
  const role = loadFixture<string>("role_system");
  assertEquals(role, "system");
  assertRoundTrip(role, "Role::System");
});

Deno.test("Role: tool variant", () => {
  const role = loadFixture<string>("role_tool");
  assertEquals(role, "tool");
  assertRoundTrip(role, "Role::Tool");
});

// ── 2. Message ───────────────────────────────────────────────────────────────

interface Message {
  role: string;
  content: string | ContentBlock[];
  name?: string;
  metadata?: unknown;
}

interface ContentBlock {
  type: string;
  [key: string]: unknown;
}

Deno.test("Message: user message", () => {
  const msg = loadFixture<Message>("message_user");
  assertEquals(msg.role, "user");
  assertEquals(typeof msg.content, "string");
  assertEquals(msg.content, "Hello, how are you?");
  assertEquals(msg.name, undefined);
  assertEquals(msg.metadata, undefined);
  assertRoundTrip(msg, "Message(user)");
});

Deno.test("Message: assistant message", () => {
  const msg = loadFixture<Message>("message_assistant");
  assertEquals(msg.role, "assistant");
  assertEquals(typeof msg.content, "string");
  assertEquals(msg.content, "I'm doing well, thank you!");
  assertRoundTrip(msg, "Message(assistant)");
});

Deno.test("Message: tool result message", () => {
  const msg = loadFixture<Message>("message_tool_result");
  assertEquals(msg.role, "tool");
  assertEquals(Array.isArray(msg.content), true);
  const blocks = msg.content as ContentBlock[];
  assertEquals(blocks.length, 1);
  assertEquals(blocks[0].type, "tool_result");
  assertEquals(blocks[0].tool_use_id, "tool-call-001");
  assertEquals(blocks[0].content, "File contents: fn main() {}");
  assertRoundTrip(msg, "Message(tool_result)");
});

// ── 3. ContentBlock ──────────────────────────────────────────────────────────

Deno.test("ContentBlock: text", () => {
  const block = loadFixture<ContentBlock>("content_block_text");
  assertEquals(block.type, "text");
  assertEquals(block.text, "Here is the analysis result.");
  assertRoundTrip(block, "ContentBlock::Text");
});

Deno.test("ContentBlock: tool_use", () => {
  const block = loadFixture<ContentBlock>("content_block_tool_use");
  assertEquals(block.type, "tool_use");
  assertEquals(block.id, "tool-call-001");
  assertEquals(block.name, "read_file");
  assertEquals((block.input as Record<string, string>).path, "/src/main.rs");
  assertRoundTrip(block, "ContentBlock::ToolUse");
});

Deno.test("ContentBlock: tool_result", () => {
  const block = loadFixture<ContentBlock>("content_block_tool_result");
  assertEquals(block.type, "tool_result");
  assertEquals(block.tool_use_id, "tool-call-001");
  assertEquals(typeof block.content, "string");
  assertRoundTrip(block, "ContentBlock::ToolResult");
});

// ── 4. Tool ──────────────────────────────────────────────────────────────────

interface ToolDef {
  name: string;
  description: string;
  input_schema: {
    type: string;
    properties?: Record<string, unknown>;
    required?: string[];
  };
  requires_approval: boolean;
  defer_loading: boolean;
  allowed_callers?: string[];
  input_examples?: unknown[];
}

Deno.test("Tool: sample tool with schema", () => {
  const tool = loadFixture<ToolDef>("tool_sample");
  assertEquals(tool.name, "read_file");
  assertEquals(
    tool.description,
    "Read the contents of a file at the given path",
  );
  assertEquals(tool.input_schema.type, "object");
  assertExists(tool.input_schema.properties);
  assertExists(tool.input_schema.properties!.path);
  assertEquals(tool.input_schema.required, ["path"]);
  assertEquals(tool.requires_approval, false);
  assertEquals(tool.defer_loading, false);
  assertRoundTrip(tool, "Tool");
});

// ── 5. ToolResult ────────────────────────────────────────────────────────────

interface ToolResult {
  tool_use_id: string;
  content: string;
  is_error: boolean;
}

Deno.test("ToolResult: success", () => {
  const result = loadFixture<ToolResult>("tool_result_success");
  assertEquals(result.tool_use_id, "tool-call-001");
  assertEquals(result.content, "Operation completed successfully");
  assertEquals(result.is_error, false);
  assertRoundTrip(result, "ToolResult(success)");
});

Deno.test("ToolResult: error", () => {
  const result = loadFixture<ToolResult>("tool_result_error");
  assertEquals(result.tool_use_id, "tool-call-002");
  assertEquals(result.content, "File not found: /nonexistent.txt");
  assertEquals(result.is_error, true);
  assertRoundTrip(result, "ToolResult(error)");
});

// ── 6. ChatOptions ───────────────────────────────────────────────────────────

interface ChatOptions {
  temperature?: number;
  max_tokens?: number;
  top_p?: number;
  stop?: string[];
  system?: string;
}

Deno.test("ChatOptions: default", () => {
  const opts = loadFixture<ChatOptions>("chat_options_default");
  assertEquals(opts.temperature, 0.7);
  assertEquals(opts.max_tokens, 4096);
  assertEquals(opts.top_p, undefined);
  assertEquals(opts.stop, undefined);
  assertEquals(opts.system, undefined);
  assertRoundTrip(opts, "ChatOptions(default)");
});

Deno.test("ChatOptions: custom with all fields", () => {
  const opts = loadFixture<ChatOptions>("chat_options_custom");
  assertEquals(opts.temperature, 0.0);
  assertEquals(opts.max_tokens, 100);
  assertEquals(opts.top_p, 0.9);
  assertEquals(opts.stop, ["\n", "END"]);
  assertEquals(opts.system, "You are a helpful assistant.");
  assertRoundTrip(opts, "ChatOptions(custom)");
});

// ── 7. TaskStatus ────────────────────────────────────────────────────────────

const TASK_STATUSES = [
  "pending",
  "inprogress",
  "completed",
  "failed",
  "blocked",
  "skipped",
] as const;

for (const status of TASK_STATUSES) {
  Deno.test(`TaskStatus: ${status}`, () => {
    const value = loadFixture<string>(`task_status_${status}`);
    assertEquals(value, status);
    assertRoundTrip(value, `TaskStatus::${status}`);
  });
}

// ── 8. TaskPriority ──────────────────────────────────────────────────────────

const TASK_PRIORITIES = ["low", "normal", "high", "urgent"] as const;

for (const priority of TASK_PRIORITIES) {
  Deno.test(`TaskPriority: ${priority}`, () => {
    const value = loadFixture<string>(`task_priority_${priority}`);
    assertEquals(value, priority);
    assertRoundTrip(value, `TaskPriority::${priority}`);
  });
}

// ── 9. Task ──────────────────────────────────────────────────────────────────

interface TaskDef {
  id: string;
  description: string;
  status: string;
  plan_id?: string;
  parent_id?: string;
  children: string[];
  depends_on: string[];
  priority: string;
  assigned_to?: string;
  iterations: number;
  summary?: string;
  created_at: number;
  updated_at: number;
  started_at?: number;
  completed_at?: number;
}

Deno.test("Task: sample task", () => {
  const task = loadFixture<TaskDef>("task_sample");
  assertEquals(task.id, "task-001");
  assertEquals(task.description, "Implement user authentication module");
  assertEquals(task.status, "pending");
  assertEquals(task.plan_id, undefined);
  assertEquals(task.parent_id, undefined);
  assertEquals(task.children, []);
  assertEquals(task.depends_on, []);
  assertEquals(task.priority, "normal");
  assertEquals(task.assigned_to, undefined);
  assertEquals(task.iterations, 0);
  assertEquals(task.summary, undefined);
  assertEquals(typeof task.created_at, "number");
  assertEquals(typeof task.updated_at, "number");
  assertEquals(task.started_at, undefined);
  assertEquals(task.completed_at, undefined);
  assertRoundTrip(task, "Task");
});

// ── 10. PlanStatus ───────────────────────────────────────────────────────────

const PLAN_STATUSES = [
  "draft",
  "active",
  "paused",
  "completed",
  "abandoned",
] as const;

for (const status of PLAN_STATUSES) {
  Deno.test(`PlanStatus: ${status}`, () => {
    const value = loadFixture<string>(`plan_status_${status}`);
    assertEquals(value, status);
    assertRoundTrip(value, `PlanStatus::${status}`);
  });
}

// ── 11. Usage ────────────────────────────────────────────────────────────────

interface UsageDef {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
}

Deno.test("Usage: sample", () => {
  const usage = loadFixture<UsageDef>("usage_sample");
  assertEquals(usage.prompt_tokens, 150);
  assertEquals(usage.completion_tokens, 50);
  assertEquals(usage.total_tokens, 200);
  assertEquals(
    usage.prompt_tokens + usage.completion_tokens,
    usage.total_tokens,
  );
  assertRoundTrip(usage, "Usage");
});

// ── 12. SearchResult ─────────────────────────────────────────────────────────

interface SearchResultDef {
  file_path: string;
  root_path: string | null;
  content: string;
  score: number;
  vector_score: number;
  keyword_score: number | null;
  start_line: number;
  end_line: number;
  language: string;
  project: string | null;
  indexed_at: number;
}

Deno.test("SearchResult: sample", () => {
  const result = loadFixture<SearchResultDef>("search_result_sample");
  assertEquals(result.file_path, "src/main.rs");
  assertEquals(result.root_path, "/home/user/project");
  assertEquals(typeof result.content, "string");
  assertEquals(result.score, 0.95);
  assertEquals(result.vector_score, 0.92);
  assertEquals(result.keyword_score, 0.88);
  assertEquals(result.start_line, 1);
  assertEquals(result.end_line, 3);
  assertEquals(result.language, "rust");
  assertEquals(result.project, "my-project");
  assertEquals(typeof result.indexed_at, "number");
  assertRoundTrip(result, "SearchResult");
});

// ── 13. PermissionMode ───────────────────────────────────────────────────────

const PERMISSION_MODES: Array<[string, string]> = [
  ["read_only", "read-only"],
  ["auto", "auto"],
  ["full", "full"],
];

for (const [fileSuffix, expected] of PERMISSION_MODES) {
  Deno.test(`PermissionMode: ${expected}`, () => {
    const value = loadFixture<string>(`permission_mode_${fileSuffix}`);
    assertEquals(value, expected);
    assertRoundTrip(value, `PermissionMode::${expected}`);
  });
}
