export interface NavItem {
  title: string;
  href?: string;
  children?: NavItem[];
}

export const NAV_TREE: NavItem[] = [
  { title: "Getting Started", href: "/" },
  { title: "Features", href: "/docs/features" },
  {
    title: "Guides",
    children: [
      { title: "Extension Points", href: "/docs/extensibility" },
      { title: "Contributing", href: "/docs/contributing" },
      { title: "Testing", href: "/docs/testing" },
      { title: "Publishing", href: "/docs/publishing" },
      { title: "Distributed Training", href: "/docs/wishlist/distributed-training" },
    ],
  },
  {
    title: "Framework Crates", href: "/crates",
    children: [
      { title: "rullama", href: "/crates/rullama" },
      { title: "rullama-core", href: "/crates/rullama-core" },
      { title: "rullama-a2a", href: "/crates/rullama-a2a" },
      { title: "rullama-skills", href: "/crates/rullama-skills" },
      { title: "rullama-permission", href: "/crates/rullama-permission" },
      { title: "rullama-call-policy", href: "/crates/rullama-call-policy" },
      { title: "rullama-sandbox", href: "/crates/rullama-sandbox" },
      { title: "rullama-provider", href: "/crates/rullama-provider" },
      { title: "rullama-provider-speech", href: "/crates/rullama-provider-speech" },
      { title: "rullama-agent", href: "/crates/rullama-agent" },
      { title: "rullama-inference", href: "/crates/rullama-inference" },
      { title: "rullama-knowledge", href: "/crates/rullama-knowledge" },
      { title: "rullama-prompting", href: "/crates/rullama-prompting" },
      { title: "rullama-rag", href: "/crates/rullama-rag" },
      { title: "rullama-reasoning", href: "/crates/rullama-reasoning" },
      { title: "rullama-mdap", href: "/crates/rullama-mdap" },
      { title: "rullama-memory", href: "/crates/rullama-memory" },
      { title: "rullama-seal", href: "/crates/rullama-seal" },
      { title: "rullama-finetune", href: "/crates/rullama-finetune" },
      { title: "rullama-datasets", href: "/crates/rullama-datasets" },
      { title: "rullama-eval", href: "/crates/rullama-eval" },
      { title: "rullama-tool-runtime", href: "/crates/rullama-tool-runtime" },
      { title: "rullama-tool-builtins", href: "/crates/rullama-tool-builtins" },
      { title: "rullama-storage", href: "/crates/rullama-storage" },
      { title: "rullama-stores", href: "/crates/rullama-stores" },
      { title: "rullama-hardware", href: "/crates/rullama-hardware" },
      { title: "rullama-mcp-client", href: "/crates/rullama-mcp-client" },
      { title: "rullama-mcp-server", href: "/crates/rullama-mcp-server" },
      { title: "rullama-network", href: "/crates/rullama-network" },
      { title: "rullama-telemetry", href: "/crates/rullama-telemetry" },
      { title: "rullama-sandbox-proxy", href: "/crates/rullama-sandbox-proxy" },
      { title: "rullama-test-fixtures", href: "/crates/rullama-test-fixtures" },
      { title: "rullama-test-harness", href: "/crates/rullama-test-harness" },
    ],
  },
  {
    title: "Extras", href: "/extras",
    children: [
      { title: "rullama-autonomy", href: "/extras/rullama-autonomy" },
      { title: "rullama-billing", href: "/extras/rullama-billing" },
      { title: "rullama-proxy", href: "/extras/rullama-proxy" },
      { title: "rullama-wasm", href: "/extras/rullama-wasm" },
      { title: "rullama-brain-server", href: "/extras/rullama-brain-server" },
      { title: "rullama-issues", href: "/extras/rullama-issues" },
      { title: "rullama-memory-server", href: "/extras/rullama-memory-server" },
      { title: "rullama-rag-server", href: "/extras/rullama-rag-server" },
      { title: "rullama-scheduler", href: "/extras/rullama-scheduler" },
      { title: "claude-brain", href: "/extras/claude-brain" },
      { title: "reload-daemon", href: "/extras/reload-daemon" },
      { title: "agent-chat", href: "/extras/agent-chat" },
      { title: "audio-demo", href: "/extras/audio-demo" },
      { title: "audio-demo-ffi", href: "/extras/audio-demo-ffi" },
      { title: "rullama-chat-native", href: "/extras/rullama-chat-native" },
      { title: "rullama-web-search-agent", href: "/extras/rullama-web-search-agent" },
      { title: "rullama-webchat", href: "/extras/rullama-webchat" },
      { title: "voice-assistant", href: "/extras/voice-assistant" },
    ],
  },
  {
    title: "Deno SDK", href: "/deno",
    children: [
      { title: "Getting Started", href: "/deno/getting-started" },
      { title: "Architecture", href: "/deno/architecture" },
      { title: "Agents", href: "/deno/agents" },
      { title: "Providers", href: "/deno/providers" },
      { title: "Tools", href: "/deno/tools" },
      { title: "Storage", href: "/deno/storage" },
      { title: "Cognition", href: "/deno/cognition" },
      { title: "Networking", href: "/deno/networking" },
      { title: "A2A Protocol", href: "/deno/a2a" },
      { title: "Permissions", href: "/deno/permissions" },
      { title: "Extensibility", href: "/deno/extensibility" },
    ],
  },
  { title: "Changelog", href: "/changelog" },
  { title: "API Reference", href: "/api-docs" },
];
