// deno-lint-ignore-file no-explicit-any

function nowTimestamp(): number {
  return Math.floor(Date.now() / 1000);
}

/** Status of a plan.
 * Equivalent to Rust's `PlanStatus` in rullama-core. */
export type PlanStatus =
  | "draft"
  | "active"
  | "paused"
  | "completed"
  | "abandoned";

/** Parse a PlanStatus from a string. */
export function parsePlanStatus(s: string): PlanStatus | undefined {
  const lower = s.toLowerCase();
  if (["draft", "active", "paused", "completed", "abandoned"].includes(lower)) {
    return lower as PlanStatus;
  }
  return undefined;
}

/** Metadata for a persisted execution plan.
 * Equivalent to Rust's `PlanMetadata` in rullama-core. */
export class PlanMetadata {
  plan_id: string;
  conversation_id: string;
  title: string;
  task_description: string;
  plan_content: string;
  model_id?: string;
  status: PlanStatus;
  executed: boolean;
  iterations_used: number;
  created_at: number;
  updated_at: number;
  file_path?: string;
  embedding?: number[];
  parent_plan_id?: string;
  child_plan_ids: string[];
  branch_name?: string;
  merged: boolean;
  depth: number;

  constructor(
    conversationId: string,
    taskDescription: string,
    planContent: string,
  ) {
    const now = nowTimestamp();
    this.plan_id = crypto.randomUUID();
    this.conversation_id = conversationId;
    this.title = (taskDescription.split("\n")[0] ?? taskDescription).slice(
      0,
      50,
    );
    this.task_description = taskDescription;
    this.plan_content = planContent;
    this.status = "draft";
    this.executed = false;
    this.iterations_used = 0;
    this.created_at = now;
    this.updated_at = now;
    this.child_plan_ids = [];
    this.merged = false;
    this.depth = 0;
  }

  /** Create a branch (sub-plan) from this plan. */
  createBranch(
    branchName: string,
    taskDescription: string,
    planContent: string,
  ): PlanMetadata {
    const branch = new PlanMetadata(
      this.conversation_id,
      taskDescription,
      planContent,
    );
    branch.parent_plan_id = this.plan_id;
    branch.branch_name = branchName;
    branch.depth = this.depth + 1;
    return branch;
  }

  /** Add a child plan ID. */
  addChild(childId: string): void {
    if (!this.child_plan_ids.includes(childId)) {
      this.child_plan_ids.push(childId);
      this.updated_at = nowTimestamp();
    }
  }

  /** Mark as merged. */
  markMerged(): void {
    this.merged = true;
    this.status = "completed";
    this.updated_at = nowTimestamp();
  }

  /** Check if this is a root plan. */
  isRoot(): boolean {
    return this.parent_plan_id === undefined;
  }

  /** Check if this plan has children. */
  hasChildren(): boolean {
    return this.child_plan_ids.length > 0;
  }

  /** Set the model used (builder). */
  withModel(modelId: string): this {
    this.model_id = modelId;
    return this;
  }

  /** Set iterations used (builder). */
  withIterations(iterations: number): this {
    this.iterations_used = iterations;
    return this;
  }

  /** Mark as executed. */
  markExecuted(): void {
    this.executed = true;
    this.status = "completed";
    this.updated_at = nowTimestamp();
  }

  /** Update status. */
  setStatus(status: PlanStatus): void {
    this.status = status;
    this.updated_at = nowTimestamp();
  }

  /** Set file path after export. */
  setFilePath(path: string): void {
    this.file_path = path;
    this.updated_at = nowTimestamp();
  }

  /** Generate markdown export with YAML frontmatter. */
  toMarkdown(): string {
    const created = new Date(this.created_at * 1000).toISOString().replace(
      /\.\d{3}Z$/,
      "Z",
    );
    const model = this.model_id ?? "unknown";
    const escapedTitle = this.title.replace(/"/g, '\\"');
    return `---
plan_id: ${this.plan_id}
conversation_id: ${this.conversation_id}
title: "${escapedTitle}"
status: ${this.status}
executed: ${this.executed}
iterations: ${this.iterations_used}
created_at: ${created}
model: ${model}
---

# Execution Plan: ${this.title}

## Original Task

${this.task_description}

## Plan

${this.plan_content}

---
*Generated by rullama*
`;
  }
}

/** A single step in a serializable pre-execution plan.
 * Equivalent to Rust's `PlanStep` in rullama-core. */
export interface PlanStep {
  step_number: number;
  description: string;
  tool_hint?: string;
  estimated_tokens: number;
}

/** Budget constraints for a serializable plan.
 * Equivalent to Rust's `PlanBudget` in rullama-core. */
export class PlanBudget {
  max_steps?: number;
  max_estimated_tokens?: number;
  max_estimated_cost_usd?: number;
  cost_per_token: number;

  constructor() {
    this.cost_per_token = 0.000003;
  }

  /** Set the maximum allowed step count (builder). */
  withMaxSteps(max: number): this {
    this.max_steps = max;
    return this;
  }

  /** Set the maximum allowed estimated token count (builder). */
  withMaxTokens(max: number): this {
    this.max_estimated_tokens = max;
    return this;
  }

  /** Set the maximum allowed estimated cost in USD (builder). */
  withMaxCostUsd(max: number): this {
    this.max_estimated_cost_usd = max;
    return this;
  }

  /** Check a plan against this budget. Returns undefined if OK, or error string. */
  check(plan: SerializablePlan): string | undefined {
    const stepCount = plan.steps.length;
    const totalTokens = plan.totalEstimatedTokens();
    const totalCost = totalTokens * this.cost_per_token;

    if (this.max_steps !== undefined && stepCount > this.max_steps) {
      return `plan has ${stepCount} steps but limit is ${this.max_steps}`;
    }
    if (
      this.max_estimated_tokens !== undefined &&
      totalTokens > this.max_estimated_tokens
    ) {
      return `plan estimates ${totalTokens} tokens but limit is ${this.max_estimated_tokens}`;
    }
    if (
      this.max_estimated_cost_usd !== undefined &&
      totalCost > this.max_estimated_cost_usd
    ) {
      return `plan estimates $${totalCost.toFixed(6)} USD but limit is $${
        this.max_estimated_cost_usd.toFixed(6)
      }`;
    }
    return undefined;
  }
}

/** A serializable execution plan.
 * Equivalent to Rust's `SerializablePlan` in rullama-core. */
export class SerializablePlan {
  plan_id: string;
  task_description: string;
  steps: PlanStep[];
  created_at: number;

  constructor(taskDescription: string, steps: PlanStep[]) {
    this.plan_id = crypto.randomUUID();
    this.task_description = taskDescription;
    this.steps = steps;
    this.created_at = nowTimestamp();
  }

  /** Sum of all estimated_tokens across steps. */
  totalEstimatedTokens(): number {
    return this.steps.reduce((sum, s) => sum + s.estimated_tokens, 0);
  }

  /** Number of steps in this plan. */
  stepCount(): number {
    return this.steps.length;
  }

  /** Parse a plan from model-generated text that contains an embedded JSON object with a "steps" array. */
  static parseFromText(
    taskDescription: string,
    text: string,
  ): SerializablePlan | undefined {
    const start = text.indexOf("{");
    const end = text.lastIndexOf("}");
    if (start === -1 || end === -1 || start > end) return undefined;

    let value: any;
    try {
      value = JSON.parse(text.slice(start, end + 1));
    } catch {
      return undefined;
    }

    const stepsArray = value?.steps;
    if (!Array.isArray(stepsArray)) return undefined;

    const steps: PlanStep[] = [];
    for (let i = 0; i < stepsArray.length; i++) {
      const step = stepsArray[i];
      const description = step?.description;
      if (typeof description !== "string") continue;

      const estimatedTokens = step?.estimated_tokens ?? step?.tokens ?? 500;
      const toolHint = step?.tool ?? step?.tool_hint;

      steps.push({
        step_number: i + 1,
        description,
        tool_hint: typeof toolHint === "string" ? toolHint : undefined,
        estimated_tokens: typeof estimatedTokens === "number"
          ? estimatedTokens
          : 500,
      });
    }

    if (steps.length === 0) return undefined;
    return new SerializablePlan(taskDescription, steps);
  }
}
