#!/bin/sh
# Rewrite build-info.js at container startup so DEV_MODE (and the build
# metadata) can be flipped at runtime without rebuilding the image.
#
# build-info.js is dynamically imported by src/ui-settings.js
# (see chat-pwa/web/src/ui-settings.js). It exports BUILD_TIME and
# BUILD_GIT today; we extend it with DEV_MODE here.
set -eu

INFO_PATH="/usr/share/nginx/html/build-info.js"

# Runtime env wins over the build-time ARG baked into the image. If both
# are unset, fall back to the values esbuild stamped in at image build.
_date="${BRAINWIRES_BUILD_DATE:-}"
_commit="${BRAINWIRES_BUILD_COMMIT:-}"
_version="${BRAINWIRES_BUILD_VERSION:-}"
_dev="${BRAINWIRES_DEV_MODE:-false}"

# Read the existing BUILD_TIME / BUILD_GIT to use as fallback when the
# ARGs above are empty (e.g. local `docker compose up --build` without
# explicit metadata args).
if [ -z "$_date" ] && [ -f "$INFO_PATH" ]; then
    _date=$(sed -n "s/.*BUILD_TIME = '\([^']*\)'.*/\1/p" "$INFO_PATH" | head -n1)
fi
if [ -z "$_commit" ] && [ -f "$INFO_PATH" ]; then
    _commit=$(sed -n "s/.*BUILD_GIT = '\([^']*\)'.*/\1/p" "$INFO_PATH" | head -n1)
fi

# Dev mode bind-mounts ./web read-only into this docroot so the host's
# esbuild output is served live. In that case we can't rewrite build-info.js
# — but the host's build.mjs already stamps DEV_MODE based on the
# launching shell's env, so the file is correct as-is.
#
# The file's mode bits may say "writable" while the underlying mount is
# read-only, so probe with a real write rather than `[ -w … ]`.
DOCROOT="$(dirname "$INFO_PATH")"
WRITE_PROBE="$DOCROOT/.entrypoint-write-probe.$$"
if (echo "" > "$WRITE_PROBE") 2>/dev/null; then
    rm -f "$WRITE_PROBE"
    cat > "$INFO_PATH" <<EOF
// generated by entrypoint.sh — do not edit
export const BUILD_TIME = '${_date}';
export const BUILD_GIT = '${_commit}';
export const BUILD_VERSION = '${_version}';
export const DEV_MODE = ${_dev};
EOF
    echo "build-info: v${_version} ${_commit} ${_date} | dev=${_dev}"
else
    echo "build-info: read-only docroot (dev bind mount) — host file authoritative"
fi

exec nginx -g 'daemon off;'
